name: pyFind
channels:
- defaults
dependencies:
- jinja2=2.9.6=py36_0
- markupsafe=0.23=py36_2
- mkl=2017.0.1=0
- numpy=1.13.0=py36_0
- openssl=1.0.2l=0
- pip=9.0.1=py36_1
- python=3.6.1=2
- readline=6.2=2
- setuptools=27.2.0=py36_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xz=5.2.2=1
- zlib=1.2.8=3
- pip:
  - pytoml==0.1.13
prefix: /opt/conda/envs/pyFind

